# Generated by Django 4.1.2 on 2022-11-02 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_release',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
